### ISSUE TITLE
Some Question about reimplement QSGD

### ISSUE THREAD

**Issue by lileilai** [saeedsoori/DeltaDNN#1]
hi, saeedsoori

i am so lucky to find the repository of the qsgd that implemented by you ,  and i  notice that their is no ReadMe . Have you already reimplement qsgd as same as the paper.

Looking forward to your reply.

**Comment by saeedsoori** [comment]
Hi, I am still working on it. This implementation is different than QSGD. Please check this one: [https://github.com/ganshaoduo/QSGD-TF](url)
